services:

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ../.env
    ports:
      - '5432:5432'
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ../.env
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    expose:
      - "8000"

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - frontend_build:/dist

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - frontend_build:/usr/share/nginx/html:ro
      - static_value:/var/html/static/
      - media_value:/var/html/media/
      - ./nginx.config:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
      - frontend


volumes:
  postgres_data:
  redis_data:
  static_value:
  media_value:
  frontend_build:
