"""empty message

Revision ID: 6e61c1610782
Revises: 3a20ff2b9462
Create Date: 2025-11-28 23:08:24.369794

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6e61c1610782"
down_revision: Union[str, Sequence[str], None] = "3a20ff2b9462"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("google_id", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.create_index(op.f("ix_user_google_id"), "user", ["google_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_google_id"), table_name="user")
    op.drop_column("user", "google_id")
    # ### end Alembic commands ###
