"""Change color class for categories

Revision ID: a8aa94bfd79a
Revises: e616dc47fa8d
Create Date: 2025-08-31 22:16:11.507197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8aa94bfd79a'
down_revision: Union[str, Sequence[str], None] = 'e616dc47fa8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('category', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('category', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.text("nextval('category_id_seq'::regclass)"),
               existing_nullable=False)
    # ### end Alembic commands ###
